# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ded811187790f3ac06fd3484a7f5ca55f4f5b82793ebf712973501803d8924a8aec8f0a46722312c4dbd5c9d46b808256dcb3ce14ec5039d48bbad899fd889a4

test:
  secret_key_base: 1d7bdf6457ebc83f39cae20d8d25eb3e7db3f32ac338eee9bff08fbe47ea6ef972f8ae2410911a164b313afcaf08f27d84a8df2d31962dbda3f894485c02a24c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
